name = "duck"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

main = "src/index.ts"

# [[d1_databases]]
# binding = "DB"
# database_name = "honc-d1-database"
# database_id = "local-honc-d1-database"
# migrations_dir = "drizzle/migrations"

# [vars]
# MY_VAR = "my-variable"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["WebSocketHibernationServer"]

[assets]
directory = "./assets"
binding = "ASSETS"
